-- sql/tables.sql

-- 1. Create a Profiles Table (Links to Supabase Auth users automatically)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    full_name TEXT,
    role TEXT DEFAULT 'operator', -- 'operator', 'manager', 'admin'
    status TEXT DEFAULT 'active'
);

-- 2. Create Accounts Table (To track balances for transactions)
CREATE TABLE public.accounts (
    account_no TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    phone_no TEXT,
    current_balance DECIMAL(15, 2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Deposits Table
CREATE TABLE public.deposits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no TEXT REFERENCES public.accounts(account_no) ON DELETE RESTRICT,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    reference_no TEXT UNIQUE,
    remarks TEXT,
    created_by UUID REFERENCES auth.users,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create Withdrawals Table
CREATE TABLE public.withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no TEXT REFERENCES public.accounts(account_no) ON DELETE RESTRICT,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    reference_no TEXT UNIQUE,
    remarks TEXT,
    created_by UUID REFERENCES auth.users,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create Expenses Table
CREATE TABLE public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL, -- 'Salary', 'Rent', 'Utilities', 'Misc'
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    expense_date DATE DEFAULT CURRENT_DATE,
    created_by UUID REFERENCES auth.users,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
